name = light_tint
title = Light Tint
author = L-Dog AND Co-Pilot 
description = Fake colored light by temporarily tinting nearby safe nodes.
optional_depends = illumination,morelights,mesecons_lightstone,unifieddyes
